# Generated by Django 4.2.16 on 2024-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lsf', 'LSF'), ('ssf', 'SSF'), ('fb', 'FB')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('common_names', models.TextField(blank=True, help_text='Comma-separated common names or synonyms')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Substrate/Medium')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pure', 'Pure'), ('composite', 'Composite'), ('amadou', 'Amadou'), ('nanopaper', 'Nanopaper'), ('scaffold', 'Scaffold'), ('3D', '3D')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('authors', models.TextField(help_text='Comma-separated list of authors')),
                ('journal', models.CharField(blank=True, max_length=100)),
                ('doi', models.URLField(blank=True, unique=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('growth_method', models.ManyToManyField(blank=True, to='fungalmaterials.growthmethod')),
                ('species', models.ManyToManyField(blank=True, to='fungalmaterials.species')),
                ('substrate', models.ManyToManyField(blank=True, to='fungalmaterials.substrate')),
                ('topic', models.ManyToManyField(blank=True, to='fungalmaterials.topic')),
            ],
        ),
    ]
