# Generated by Django 4.2.16 on 2024-10-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="method",
            field=models.ManyToManyField(blank=True, to="fungalmaterials.method"),
        ),
    ]
