# Generated by Django 4.2.16 on 2024-10-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0002_article_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Property Names',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungalmaterials.propertyname'),
        ),
    ]
