# Generated by Django 4.2.16 on 2024-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0003_propertyname_alter_property_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('article',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='method',
        ),
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ManyToManyField(blank=True, to='fungalmaterials.topic'),
        ),
    ]
