# Generated by Django 4.2.16 on 2024-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0004_alter_material_unique_together_remove_article_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=2300),
        ),
    ]
