# Generated by Django 4.2.16 on 2024-09-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0005_alter_article_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='common_names',
            new_name='alternative_names',
        ),
    ]
