# Generated by Django 4.2.16 on 2024-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0007_species_phylum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('authors', models.TextField(blank=True, help_text='Comma-separated list of authors')),
                ('journal', models.CharField(blank=True, max_length=100)),
                ('doi', models.URLField(blank=True, max_length=100, unique=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.URLField(blank=True, max_length=100, unique=True),
        ),
    ]
