# Generated by Django 4.2.16 on 2024-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0016_alter_article_year_alter_review_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter author names as: last name, first name (e.g. Smith, Jane)', max_length=50, unique=True, verbose_name='Author(s)')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Please enter author names as: last name, first name (e.g. Smith, Jane)', to='fungalmaterials.author', verbose_name='Author(s)'),
        ),
        migrations.AddField(
            model_name='review',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Please enter author names as: last name, first name (e.g. Smith, Jane)', to='fungalmaterials.author', verbose_name='Author(s)'),
        ),
    ]
