# Generated by Django 4.2.16 on 2024-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0019_property_unit_materialproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialproperty',
            options={'verbose_name_plural': 'Material properties'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the unit (e.g. grams per cubic centimeter)', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(help_text='Symbol of the unit (e.g. g/cm³)', max_length=10, unique=True),
        ),
    ]
