# Generated by Django 4.2.16 on 2024-09-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0023_author_affiliation_author_family_author_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='authors',
        ),
    ]
