# Generated by Django 4.2.16 on 2024-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungalmaterials', '0025_remove_author_affiliation_remove_author_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthorship',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='author',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
