# Generated by Django 4.2.16 on 2024-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0026_remove_articleauthorship_affiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
