# Generated by Django 4.2.16 on 2024-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0029_alter_review_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="doi",
            field=models.URLField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
