# Generated by Django 4.2.16 on 2024-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0031_alter_article_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="doi",
            field=models.URLField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
