# Generated by Django 4.2.16 on 2024-10-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0032_alter_article_title_alter_review_doi_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MaterialProperty",
            new_name="Material",
        ),
    ]
