# Generated by Django 4.2.16 on 2024-10-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0033_rename_materialproperty_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name_plural": "Materials"},
        ),
    ]
