# Generated by Django 4.2.16 on 2024-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_species_options_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthmethod',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
