# Generated by Django 4.2.16 on 2024-09-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_growthmethod_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowthMethod',
            new_name='Method',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='growth_method',
            new_name='method',
        ),
    ]
