# Generated by Django 4.2.16 on 2024-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_growthmethod_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.TextField(blank=True, help_text='Comma-separated list of authors'),
        ),
    ]
