# Generated by Django 4.2.16 on 2024-09-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_common_names_species_alternative_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='phylum',
            field=models.CharField(blank=True, choices=[('Basidiomycota', 'Basidiomycota'), ('Ascomycota', 'Ascomycota'), ('Blastocladiomycota', 'Blastocladiomycota'), ('Mycoromycota', 'Mycoromycota'), ('Opisthosporidia', 'Opisthosporidia')], max_length=20),
        ),
    ]
