# Generated by Django 4.2.16 on 2024-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_alter_article_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='topic',
            field=models.ManyToManyField(blank=True, to='main.topic'),
        ),
    ]
