# Generated by Django 4.2.16 on 2024-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'doi')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'doi')},
        ),
    ]
