# Generated by Django 4.2.16 on 2024-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_article_year_alter_review_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='review',
            name='abstract',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
